{% set name = "streamad" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamad-{{ version }}.tar.gz
  sha256: afb879e2bd774ec1042f6876bee836e1b74d535efcfda344879f71755d0ed99d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools ==58.2.0
  run:
    - mmh3 >=3.0.0
    - numpy >=1.19
    - pandas >=1.3.0
    - plotly
    - python >={{ python_min }}
    - scikit-learn >=1.0.0
    - scipy >=1.7.0

test:
  imports:
    - streamad
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Fengrui-Liu/StreamAD
  summary: An anomaly detection package for data streams.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Fengrui-Liu
